name: Dev CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dev Environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/edu-track-api-dev
            git pull origin main
            sudo bash dev-deploy.sh
            exit

